#!/usr/bin/env bash
# Bootstrap verification: ensure required governance, runtime, and integration paths exist.
# Run after cloning or restoring a generated workspace.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MISSING=0

echo "==> Bootstrap: verifying Agentic SDLC layer at $ROOT"

# Projects may use memory_bank/ (framework default) or memory-bank/ (legacy).
MEMORY_DIR="memory_bank"
HAS_HYPHEN=false
HAS_UNDERSCORE=false
[ -d "$ROOT/memory-bank" ] && HAS_HYPHEN=true
[ -d "$ROOT/memory_bank" ] && HAS_UNDERSCORE=true

if $HAS_HYPHEN && ! $HAS_UNDERSCORE; then
  MEMORY_DIR="memory-bank"
  echo "  DETECTED: memory-bank/ (hyphen convention)"
elif $HAS_UNDERSCORE && ! $HAS_HYPHEN; then
  echo "  Using: memory_bank/ (underscore convention)"
elif $HAS_HYPHEN && $HAS_UNDERSCORE; then
  if [ -f "$ROOT/memory-bank/activeContext.md" ] || [ -f "$ROOT/memory-bank/productContext.md" ]; then
    MEMORY_DIR="memory-bank"
    echo "  DETECTED: both exist. Using memory-bank/ (has project content)."
  else
    echo "  Both exist. Using memory_bank/ (framework default)."
  fi
else
  echo "  Creating: memory_bank/ (framework default)"
  mkdir -p "$ROOT/memory_bank/snapshots"
fi

mkdir -p "$ROOT/.agent"
cat > "$ROOT/.agent/project-config.md" << PROJECTCONFIG
# Project Configuration

> Auto-generated by bootstrap.sh. Do not edit manually.

- **MEMORY_DIR:** \`$MEMORY_DIR\`
PROJECTCONFIG

for path in \
  ".gitignore" \
  "AGENTS.md" \
  "CLAUDE.md" \
  "PROJECT_MAP.md" \
  "FILE_REGISTRY.yml" \
  "governance/README.md" \
  "governance/authority.md" \
  "governance/lifecycle.md" \
  "governance/artifacts.md" \
  "governance/runtime-capabilities.md" \
  "runtimes/README.md" \
  "runtimes/codex/README.md" \
  "runtimes/claude-code/README.md" \
  "runtimes/opencode/README.md" \
  "runtimes/generic/README.md" \
  "integrations/README.md" \
  "integrations/claude-code-codex-plugin/README.md" \
  "integrations/mcp/README.md" \
  "integrations/file-handoff/README.md" \
  ".agent/ROSTER.md" \
  ".agent/active-work-block.json" \
  ".agent/critic-gate.md" \
  ".agent/verification-gate.md" \
  ".agent/hooks/hard_stop_policy.py" \
  ".agent/workflows/sdd-protocol.md" \
  ".agent/skills/README.md" \
  ".agent/skills/spec-drift-audit/SKILL.md" \
  ".mcp.json" \
  ".claude/settings.json" \
  ".claude/agent-memory/critic/MEMORY.md" \
  ".claude/agent-memory/reviewer/MEMORY.md" \
  ".claude/agent-memory/scoped-coder/MEMORY.md" \
  ".claude/agent-memory/solution-architect/MEMORY.md" \
  ".claude/agent-memory/verifier/MEMORY.md" \
  ".claude/agents/solution-architect.md" \
  ".claude/agents/critic.md" \
  ".claude/agents/scoped-coder.md" \
  ".claude/agents/reviewer.md" \
  ".claude/agents/verifier.md" \
  ".claude/hooks/work_block_gate.py" \
  ".claude/hooks/assurance_gate.py" \
  ".claude/hooks/critic-gate.sh" \
  ".claude/hooks/hard-stop.sh" \
  ".claude/hooks/typecheck.sh" \
  ".claude/hooks/verification-gate.sh" \
  ".claude/skills/README.md" \
  ".codex/config.toml.template" \
  ".codex/critic.md" \
  ".codex/write-gate.md" \
  ".codex/hooks.json" \
  ".codex/agents/architect.toml" \
  ".codex/agents/critic.toml" \
  ".codex/agents/coder.toml" \
  ".codex/agents/reviewer.toml" \
  ".codex/agents/verifier.toml" \
  ".codex/hooks/hard_stop_policy.py" \
  ".codex/hooks/pre_tool_use_policy.py" \
  ".codex/hooks/stage0_write_gate.py" \
  ".codex/hooks/subagent_context.py" \
  "opencode.json" \
  ".opencode/agents/architect.md" \
  ".opencode/agents/critic.md" \
  ".opencode/agents/coder.md" \
  ".opencode/agents/reviewer.md" \
  ".opencode/agents/verifier.md" \
  "docs/session-bootstrap.md" \
  "docs/engineering-memory/README.md" \
  "docs/engineering-memory/decision-record-template.md" \
  "docs/engineering-memory/source-of-truth-chains.md" \
  "docs/engineering-memory/temporary-decisions.md" \
  "docs/engineering-memory/reproducibility-log.md" \
  "docs/plans/README.md" \
  "docs/specs/README.md" \
  "docs/tasklist/README.md" \
  "docs/reports/README.md" \
  "docs/templates/work-block-template.md" \
  "docs/templates/spec-drift-report-template.md" \
  "docs/templates/integration-admission-template.md" \
  "$MEMORY_DIR/context.md" \
  "$MEMORY_DIR/progress.md" \
  "$MEMORY_DIR/decisions.md" \
  "$MEMORY_DIR/orchestrator-log.md" \
  "$MEMORY_DIR/review-log.md" \
  "$MEMORY_DIR/external-team-log.md" \
  "$MEMORY_DIR/snapshots/.gitkeep"; do
  if [ ! -f "$ROOT/$path" ]; then
    echo "  MISSING: $path"
    MISSING=1
  else
    echo "  OK: $path"
  fi
done

# Provider-named compatibility agents are intentionally absent from new projects.
for path in \
  ".claude/agents/gpt-critic.md" \
  ".claude/agents/gpt-verifier.md" \
  ".claude/agents/codex-reviewer.md" \
  ".claude/agent-memory/gpt-critic/MEMORY.md" \
  ".claude/agent-memory/gpt-verifier/MEMORY.md" \
  ".claude/agent-memory/codex-reviewer/MEMORY.md"; do
  if [ -e "$ROOT/$path" ]; then
    echo "  UNEXPECTED: $path"
    MISSING=1
  else
    echo "  OK absent: $path"
  fi
done

if [ "$MISSING" -eq 1 ]; then
  echo "==> Agentic SDLC layer incomplete — review paths above."
  exit 1
fi

echo "==> Agentic SDLC layer: OK"

echo ""
echo "==> Dev environment checks..."
if [ -d "$ROOT/node_modules" ]; then
  echo "  OK: node_modules/"
else
  echo "  WARN: node_modules/ missing — install dependencies when this project requires them"
fi

if [ -n "${DATABASE_URL:-}" ]; then
  echo "  OK: DATABASE_URL is set"
elif [ -f "$ROOT/.env" ] && grep -q "DATABASE_URL" "$ROOT/.env" 2>/dev/null; then
  echo "  OK: DATABASE_URL found in .env"
else
  echo "  WARN: DATABASE_URL not set — database-dependent checks may be blocked"
fi

echo "==> Dev environment checks done"
